// <auto-generated />
using CodeFirstApproach.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstApproach.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstApproach.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Vaishali",
                            Country = "India",
                            State = "Bihar",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Lalaganj",
                            Country = "India",
                            State = "UtterPradesh",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            City = "Patna",
                            Country = "India",
                            State = "Bihar",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("CodeFirstApproach.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Maheru"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jalandhar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phaghwara"
                        });
                });

            modelBuilder.Entity("CodeFirstApproach.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Mathematics"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Science"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Hindi"
                        });
                });

            modelBuilder.Entity("CodeFirstApproach.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Email = "Kundan@gmail.com",
                            Name = "Kundan",
                            PhoneNumber = 123456534,
                            StudentId = 0
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            Email = "Nikhil@gmail.com",
                            Name = "Nikhil",
                            PhoneNumber = 345342342,
                            StudentId = 0
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 3,
                            Email = "Gaurav@gmail.com",
                            Name = "Gaurav",
                            PhoneNumber = 892873433,
                            StudentId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
